//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Vet.rc
//
#define IDC_MYICON                      2
#define TXT_CEDULA_MODINFO              55
#define TXT_PASSWORD_CONFIRM_MODINFO    77
#define IDD_DEMOCIOOPA_DIALOG           102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_VET                         107
#define IDI_SMALL                       108
#define IDC_DEMOCIOOPA                  109
#define IDC_MENU                        109
#define IDR_MAINFRAME                   128
#define VET_LOGIN                       129
#define IDD_LOGIN                       129
#define VET_PRINCIPAL                   130
#define IDD_HOME                        130
#define VET_EDITCONTROL                 131
#define IDD_CITAS                       131
#define IDD_DIALOG1                     132
#define IDD_INFO                        132
#define IDD_DIALOG2                     133
#define IDD_Agenda                      133
#define IDD_MODINFO                     134
#define IDD_REGISTER                    135
#define TXT_NOMBRE_MODINFO              444
#define LOGIN                           1000
#define BTN_INGRESA_IN                  1000
#define REGISTRO                        1001
#define BTN_REGISTRO_IN                 1001
#define PRINCIPAL_MOVER                 1002
#define VET_NOMBRE                      1003
#define IDC_BUTTON1                     1004
#define BTN_CANCELAR_CITAS              1004
#define BTN_MODIFICAR_INFO              1004
#define BTN_CANCELAR_MODINFO            1004
#define BTN_RECIENTE                    1004
#define IDC_BUTTON2                     1005
#define BTN_REGISTRAR_CITAS             1005
#define BTN_GUARDAR_MODINFO             1005
#define BTN_VIEJO                       1005
#define IDC_DATETIMEPICKER1             1006
#define IDC_DATETIMEPICKER2             1007
#define IDC_LIST1                       1008
#define BTN_MODIFICAR_AGENDA            1008
#define LIST_ESPECIE_CITAS              1008
#define IDC_COMBO1                      1009
#define LIST_ESTATUS                    1009
#define LIST_ESTATUS_AGENDA             1009
#define IDC_COMBO2                      1010
#define IDC_RADIO1                      1011
#define LIST_ESPECIE_AGENDA             1011
#define IDC_RADIO2                      1012
#define IDC_RADIO3                      1013
#define IDC_CHECK1                      1014
#define IDC_CHECK2                      1015
#define IDC_CHECK3                      1016
#define IDC_FOTO1                       1017
#define TXT_PASSWORD_MODINFO            1017
#define IDC_EDIT1                       1018
#define TXT_NOMBRE_AGENDA               1018
#define IDC_EDIT2                       1019
#define TXT_ESPECIE_AGENDA              1019
#define IDC_FECHA                       1019
#define IDC_BUTTON3                     1020
#define TXT_CEDULA_INFO                 1020
#define IDC_EDIT3                       1020
#define TXT_PASSWORD_IN                 1020
#define TXT_TEL_AGENDA                  1020
#define BTN_ESPECIFICAR                 1020
#define TXT_CLAVE_INFO                  1021
#define TXT_MASCOTA_AGENDA              1021
#define TXT_USUARIO_INFO                1021
#define TXT_PASSWORD_INFO               1022
#define TXT_COSTO_AGENDA                1022
#define TXT_NMB_DOC_INFO                1023
#define TXT_ESTATUS_AGENDA              1023
#define IDC_EDIT4                       1023
#define IDC_HORA                        1023
#define BTN_CAMBIAR_IMG_INFO            1024
#define TXT_USUARIO_IN                  1025
#define BTN_CANCELAR_AGENDA             1026
#define BTN_REGISTRAR_AGENDA            1027
#define LIST_AGENDA                     1028
#define CALENDARIO_AGENDA               1029
#define FECHA_SELECT_CITAS              1030
#define HORA_SELECT_CITAS               1031
#define BTN_ESPECIFICAR_CITAS           1032
#define TXT_NOMBRE_CITAS                1033
#define TXT_TEL_CITAS                   1034
#define TXT_MASCOTA_CITAS               1035
#define TXT_COSTO_CITAS                 1036
#define TXT_ESTATUS_CITAS               1037
#define TXT_USUARIO_MODINFO             1038
#define BTN_ATRAS_REGISTRO              1039
#define BTN_REGISTRAR_REGISTRO          1040
#define TXT_USUARIO_REGISTRO            1041
#define TXT_PASSWORD_REGISTRO           1042
#define TXT_PASSWORD_CONFIRM_REGISTRO   1043
#define TXT_NOMBRE_REGISTRO             1044
#define TXT_CEDULA_REGISTRO             1045
#define Seleccionar                     1046
#define BTN_SLC_IMG_REGISTRO            1046
#define IMG_FPERFIL_REGISTRO            1047
#define TXT_PROXCITAS                   1048
#define IMG_FPERFIL_MENU                1049
#define IMG_FPERFIL_AGENDA              1053
#define IMG_FPERFIL_CITAS               1054
#define IMG_FPERFIL_INFO                1055
#define TXT_RUTA                        1056
#define TXT_RUTA1                       1057
#define NOMBRE_AGENDA                   1058
#define NOMBRE_CITAS                    1059
#define BTN_NUEVO                       1062
#define BTN_LIMPIAR_CITAS               1063
#define BTN_SIGUIENTES                  1064
#define BTN_PASADAS2                    1065
#define BTN_PASADAS                     1065
#define ID_ARCHIVO_OPCION2              32771
#define ID_OPCION1                      32772
#define ID_ARCHIVO_VENTANAEDIT          32773
#define ID_ARCHIVO_VENTANAEJEMPLO8      32774
#define ID_ARCHIVO_VENTANA9             32775
#define ID_Perfil                       32776
#define ID_Agenda                       32777
#define ID_CITAS                        32778
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
